"""
Authorization Code Service — generation, validation, and expiry logic.

Codes use format: LH-XXXX-XXXX
Alphabet excludes confusable characters (0/O, 1/I/L) for phone-readability.
"""

import secrets
from datetime import datetime, timedelta, timezone

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.models import AuthorizationCode, Member

# Safe alphabet: A-Z + 2-9, excluding 0/O, 1/I/L
_SAFE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def generate_code() -> str:
    """Generate a unique, non-guessable authorization code in LH-XXXX-XXXX format."""
    seg1 = "".join(secrets.choice(_SAFE_ALPHABET) for _ in range(4))
    seg2 = "".join(secrets.choice(_SAFE_ALPHABET) for _ in range(4))
    return f"LH-{seg1}-{seg2}"


def generate_unique_code(db: Session) -> str:
    """Generate a code and ensure it doesn't collide with existing codes."""
    for _ in range(10):
        code = generate_code()
        exists = (
            db.query(AuthorizationCode.id)
            .filter(AuthorizationCode.code == code)
            .first()
        )
        if not exists:
            return code
    raise RuntimeError("Failed to generate unique authorization code after 10 attempts")


def create_authorization_code(
    db: Session,
    *,
    member: Member,
    approved_amount: float,
    visit_type: str,
    notes: str | None,
    agent_id: str,
    agent_name: str,
) -> AuthorizationCode:
    """Create a new authorization code for a member."""
    code = generate_unique_code(db)
    expires_at = datetime.now(timezone.utc) + timedelta(
        hours=settings.AUTH_CODE_EXPIRY_HOURS
    )

    auth_code = AuthorizationCode(
        code=code,
        member_id=member.member_id,
        enrollee_id=member.enrollee_id,
        approved_amount=approved_amount,
        visit_type=visit_type,
        notes=notes,
        agent_id=agent_id,
        agent_name=agent_name,
        status="active",
        expires_at=expires_at,
    )
    db.add(auth_code)
    db.commit()
    db.refresh(auth_code)
    return auth_code


def validate_authorization_code(
    db: Session, *, code: str, enrollee_id: str
) -> tuple[bool, str, AuthorizationCode | None]:
    """
    Validate an authorization code.

    Returns (is_valid, message, auth_code_or_None).

    Checks:
    1. Code exists
    2. Code matches the enrollee
    3. Code is not expired
    4. Code is not already used
    """
    auth_code = (
        db.query(AuthorizationCode)
        .filter(AuthorizationCode.code == code.upper().strip())
        .first()
    )

    if not auth_code:
        return False, "Authorization code not found.", None

    if auth_code.enrollee_id != enrollee_id.strip():
        return False, "Authorization code does not match this member.", None

    if auth_code.status == "used":
        return False, "Authorization code has already been used.", None

    if auth_code.status == "expired":
        return False, "Authorization code has expired.", None

    if datetime.now(timezone.utc) > auth_code.expires_at:
        # Mark as expired
        auth_code.status = "expired"
        db.commit()
        return False, "Authorization code has expired.", None

    return True, "Authorization code is valid.", auth_code


def mark_code_used(
    db: Session, *, auth_code: AuthorizationCode, claim_id: str
) -> None:
    """Atomically mark an authorization code as used and link it to a claim."""
    auth_code.status = "used"
    auth_code.linked_claim_id = claim_id
    db.commit()


def expire_stale_codes(db: Session) -> int:
    """
    Mark all active codes past their expiry as expired.
    Returns the count of newly expired codes.
    """
    now = datetime.now(timezone.utc)
    count = (
        db.query(AuthorizationCode)
        .filter(
            AuthorizationCode.status == "active",
            AuthorizationCode.expires_at < now,
        )
        .update({"status": "expired"})
    )
    db.commit()
    return count


def get_codes_by_agent(
    db: Session, *, agent_id: str, skip: int = 0, limit: int = 50
) -> tuple[list[AuthorizationCode], int]:
    """Get authorization codes generated by a specific agent."""
    query = (
        db.query(AuthorizationCode)
        .filter(AuthorizationCode.agent_id == agent_id)
        .order_by(AuthorizationCode.created_at.desc())
    )
    total = query.count()
    codes = query.offset(skip).limit(limit).all()
    return codes, total


def get_codes_by_enrollee(
    db: Session, *, enrollee_id: str
) -> list[AuthorizationCode]:
    """Get all authorization codes for a member."""
    return (
        db.query(AuthorizationCode)
        .filter(AuthorizationCode.enrollee_id == enrollee_id)
        .order_by(AuthorizationCode.created_at.desc())
        .all()
    )
